// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3yvGp_UzkrecIRMehiVdwFCuMGUWH9JI',
    appId: '1:579485415316:web:7b66d18ee0b290962f4181',
    messagingSenderId: '579485415316',
    projectId: 'humsafar-khoj',
    authDomain: 'humsafar-khoj.firebaseapp.com',
    databaseURL: 'https://humsafar-khoj-default-rtdb.firebaseio.com',
    storageBucket: 'humsafar-khoj.firebasestorage.app',
    measurementId: 'G-CTWN599GBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wqyB8YQzrhBtCf9lw83N02E8JXwZxzA',
    appId: '1:579485415316:android:a3c89c2e8e442fb22f4181',
    messagingSenderId: '579485415316',
    projectId: 'humsafar-khoj',
    databaseURL: 'https://humsafar-khoj-default-rtdb.firebaseio.com',
    storageBucket: 'humsafar-khoj.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3yvGp_UzkrecIRMehiVdwFCuMGUWH9JI',
    appId: '1:579485415316:web:97442746dc3b46112f4181',
    messagingSenderId: '579485415316',
    projectId: 'humsafar-khoj',
    authDomain: 'humsafar-khoj.firebaseapp.com',
    databaseURL: 'https://humsafar-khoj-default-rtdb.firebaseio.com',
    storageBucket: 'humsafar-khoj.firebasestorage.app',
    measurementId: 'G-CCY9L9869R',
  );
}
